GSK-342/task Added the case where prediction is constant after perturbation
Giskard-AI/giskard-client pull request #53
Opened 2022-11-16 13:30 UTC by rabah-khalek

`stats.wilcoxon(population_1, population_2, alternative=alternative)` was failing when `population_1==population_2`. I added an if statement to avoid this issue.

2022-11-21 17:38 UTC, andreybavt requested changes
@rabah-khalek could you implement unit tests for the new code?

2022-11-21 17:38 UTC, andreybavt commented on giskard/ml_worker/testing/stat_utils.py
> +        stat, p_value = stats.ttest_rel(population_1, population_2, alternative=alternative)
```suggestion
        _, p_value = stats.ttest_rel(population_1, population_2, alternative=alternative)
```

it's common to replace unused variables with `_`

2022-11-21 17:38 UTC, andreybavt commented on giskard/ml_worker/testing/stat_utils.py
>      if p_value > critical_quantile:
this whole if-else block can be just 
```
return p_value <= critical_quantile, p_value
```

2022-11-22 11:36 UTC, rabah-khalek commented
@andreybavt, I implemented all your suggestion and I:
- re-debugged all the stat tests after the modifications, all cases are working as expected.
- I splitted the unit tests into direction and invariance based on their case (they were all in invariance before).
- removed some overlooked `return` in unit tests
- improvied the coverage of giskard/ml_worker/testing/stat_utils.py up to 95%.

2022-11-22 13:11 UTC, merged